name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
    - name: Build Docker image
      run: docker build -t expanse-backend:tagname .

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      run: docker run -p 8080:8080 -e NODE_ENV=production -d expanse-backend:tagname
      
